fix: adjust mutex handling around ddwaf_context
DataDog/go-libddwaf pull request #52
Opened 2023-12-04 14:43 UTC by RomainMuller

- Removes a leftover mutex on `Handle` that no longer served any purpose
- Acquiring the mutex on `Context` prior to calling `ddwaf_context_destroy` to avoid concurrent calls to `ddwaf_run`, as these are not thread-safe.

APPSEC-12585

2023-12-05 08:41 UTC, eliottness approved these changes

2023-12-05 09:01 UTC, Hellzy approved these changes

2023-12-05 16:12 UTC, Julio-Guerra requested changes

2023-12-05 16:12 UTC, Julio-Guerra commented on context.go
> +	defer context.handle.Close() // Reduce the reference counter of the Handle.
```suggestion
	defer context.handle.release() // Reduce the reference counter of the Handle.
```

2023-12-05 16:16 UTC, RomainMuller commented on context.go
> +	cContext wafContext // The C ddwaf_context pointer
The field ordering here is determined by `betteralign` to minimize the pointer surface for the Go garbage collector.

2023-12-05 16:17 UTC, RomainMuller commented on handle.go
> +				return 0
I'd panic if this didn't mean possibly crashing a customer application because of a WAF bug...?

2023-12-05 16:18 UTC, RomainMuller commented on waf_test.go
> +				time.Sleep(time.Microsecond)
This gives us CPU-scheduler-supported randomness of execution order :)

2023-12-05 22:44 UTC, Julio-Guerra requested changes
Full pass done.
Please let me know when you need a final review :-)

2023-12-05 22:44 UTC, Julio-Guerra commented on context.go
> -
Indeed no longer needed because we are by construction only reading the handle once instantiated.

2023-12-05 22:44 UTC, Julio-Guerra commented on context.go
> +	defer context.handle.Close() // Reduce the reference counter of the Handle.
```suggestion
	defer context.handle.release() // Reduce the reference counter of the Handle.
```

2023-12-05 22:44 UTC, Julio-Guerra commented on context.go
>  // Close calls handle.closeContext which calls ddwaf_context_destroy and maybe also close the handle if it in termination state.
```suggestion
// Close the ddwaf_context and associated internal data. Also decreases the number of
// references to the ddwaf_handle of the context, which possibly releases it if this is the
// last context referencing it.
```

2023-12-05 22:44 UTC, Julio-Guerra commented on context.go
> +	defer context.mutex.Unlock()
So this is where the mutex lock was forgotten indeed. Very good catch.

Note: having concurrent calls to wafCtx.Run and wafCtx.Close doesn't happen in the current way we instrument. But it's definitely worth making it correct.

2023-12-05 22:44 UTC, Julio-Guerra commented on handle.go
> +				return 0
It's something I always struggle to decide. But I like to raise something in case of unexpected behaviours, such as a telemetry metric, an error log, a panic, etc.

One of our tasks in the backlog is to add panic recovering in all our go-libddwaf API to be able to gracefully return an error in case of a panic (and gracefully try to handle it).

My conclusion is: if you agree this case is an unexpected behaviour, let's at least add a TODO saying to raise some kind of future signal (error, panic, whatever).

2023-12-07 09:47 UTC, Julio-Guerra approved these changes

2023-12-07 09:56 UTC, merged