feat: return input truncation information from Context.Run
DataDog/go-libddwaf pull request #73
Opened 2024-02-26 10:54 UTC by RomainMuller

In order to allow producing instrumentation telemetry, and to be able to annotate ASM-enabled trace spans with truncation signals, we need to surface truncation information through the `waf.Result` structure.

2024-02-26 13:56 UTC, eliottness requested changes
Rebase to get the new faster CI :+1:

2024-02-26 13:56 UTC, eliottness commented on waf.go
> +	Truncations map[TruncationReason][]int
At this point you can document all the fields of the `Result` struct I guess

2024-02-26 13:56 UTC, eliottness commented on encoder.go
> +	// ObjectTooDeepn indicates an overall object exceeded the maximum encoding depths configured. The
```suggestion
	// ObjectTooDeep indicates an overall object exceeded the maximum encoding depths configured. The
```

2024-02-27 09:22 UTC, Hellzy approved these changes

2024-02-27 11:53 UTC, eliottness approved these changes

2024-02-27 12:57 UTC, merged